# Tells GitHub to remove .html from URLs
permalink: /:basename

defaults:
  - scope:
      path: "/posts/"
    values:
      permalink: /:basename

# Tells GitHub NOT to process these files
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - generate-sitemap.js
  - .github
