backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Devotional Posts"
    folder: "_posts"
    create: true
    # Removed {{year}}-{{month}}-{{day}} to make the URL clean
    slug: "{{slug}}" 
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
